### ISSUE TITLE
Disable the argument `max_execution`

### ISSUE THREAD

**Issue by Mohannadcse** [tdurieux/EnergiBridge#3]
It's not clear how to disable this flag. 
The documentation shows setting the value to `-1` can disable it. 
- https://github.com/tdurieux/EnergiBridge/blob/513c41662932d8993b3c1c06cbd5835508d6bb44/src/main.rs#L42
- https://github.com/tdurieux/EnergiBridge/blob/513c41662932d8993b3c1c06cbd5835508d6bb44/README.md?plain=1#L92

I tried these commands 
- `./energibridge --max-execution -1 -- docker pull nginx` received this error `error: a value is required for '--max-execution <MAX_EXECUTION>' but none was supplied`
- `./energibridge --max-execution -- -1 -- docker pull nginx` received this error 
```
error: unexpected argument '-1' found

  tip: to pass '-1' as a value, use '-- -1'

Usage: energibridge [OPTIONS] [COMMAND]...
```

**Comment by tdurieux** [comment]
Fixed doc
