### ISSUE TITLE
EnergiBridge not showing total energy usage

### ISSUE THREAD

**Issue by aron-hoogeveen** [tdurieux/EnergiBridge#5]
Expected behaviour: after running the tool with the `--summary` option, a summary is shown.
Actual behaviour: no summary is shown.

System information: 

> OS: Ubuntu 22.04.3 LTS
> Graphics card: NVIDIA GeForce RTX 4070 Laptop GPU/PCIe/SSE2 / NVIDIA Corporation
> Processor: AMD® Ryzen 9 7940hs w/ radeon 780m graphics × 16
> Rustc: 1.76.0 (07dca489a 2024-02-04)

I followed the instructions as provided in the main readme file. I built both from the 0.0.4 tagged release (dab662f) and from main (currently at 8ab8a7e). When I run the tool (using sudo, as I cannot seem to get the `setcap` capabilities to work, but that is possibly a different problem) I get the following output:

> aron@aron-asus:~/Downloads/EnergiBridge$ sudo target/release/energibridge --summary sleep 5
Delta,Time,CORE0_ENERGY (J),CORE0_FREQ (MHZ),CORE0_PSTATE,CORE0_VOLT (V),CORE1_ENERGY (J),CORE1_FREQ (MHZ),CORE1_PSTATE,CORE1_VOLT (V),CORE2_ENERGY (J),CORE2_FREQ (MHZ),CORE2_PSTATE,CORE2_VOLT (V),CORE3_ENERGY (J),CORE3_FREQ (MHZ),CORE3_PSTATE,CORE3_VOLT (V),CORE4_ENERGY (J),CORE4_FREQ (MHZ),CORE4_PSTATE,CORE4_VOLT (V),CORE5_ENERGY (J),CORE5_FREQ (MHZ),CORE5_PSTATE,CORE5_VOLT (V),CORE6_ENERGY (J),CORE6_FREQ (MHZ),CORE6_PSTATE,CORE6_VOLT (V),CORE7_ENERGY (J),CORE7_FREQ (MHZ),CORE7_PSTATE,CORE7_VOLT (V),CPU_ENERGY (J),CPU_FREQUENCY_0,CPU_FREQUENCY_1,CPU_FREQUENCY_10,CPU_FREQUENCY_11,CPU_FREQUENCY_12,CPU_FREQUENCY_13,CPU_FREQUENCY_14,CPU_FREQUENCY_15,CPU_FREQUENCY_2,CPU_FREQUENCY_3,CPU_FREQUENCY_4,CPU_FREQUENCY_5,CPU_FREQUENCY_6,CPU_FREQUENCY_7,CPU_FREQUENCY_8,CPU_FREQUENCY_9,CPU_USAGE_0,CPU_USAGE_1,CPU_USAGE_10,CPU_USAGE_11,CPU_USAGE_12,CPU_USAGE_13,CPU_USAGE_14,CPU_USAGE_15,CPU_USAGE_2,CPU_USAGE_3,CPU_USAGE_4,CPU_USAGE_5,CPU_USAGE_6,CPU_USAGE_7,CPU_USAGE_8,CPU_USAGE_9,TOTAL_MEMORY,TOTAL_SWAP,USED_MEMORY,USED_SWAP
> 0,1707917275021,630.1700744628906,2050,2,0.6,578.3262939453125,2050,2,0.6,526.1162567138672,2050,2,0.6,640.6179046630859,2050,2,0.6,618.1063995361328,2050,2,0.6,820.3927764892578,2050,2,0.6,537.5810546875,5125,0,0.6,540.7541961669922,2050,2,0.6,6031.795822143555,4302,2035,2250,2035,3077,2544,400,3874,2036,400,2215,3390,2141,2793,4683,2061,0,0,3.4482758045196533,3.4482758045196533,3.4482758045196533,0,3.4482758045196533,3.4482758045196533,0,0,0,0,3.4482758045196533,3.4482758045196533,0,3.4482758045196533,15930789888,0,4163850240,0
200,1707917275021,630.1703186035156,2050,2,0.6,578.3263244628906,2050,2,0.012499999999999956,526.1162719726563,2050,2,0.012499999999999956,640.617919921875,2050,2,0.012499999999999956,618.1102294921875,2050,2,0.012499999999999956,820.3927917480469,2050,2,0.012499999999999956,537.5830535888672,5125,0,0.012499999999999956,540.7605743408203,5125,0,0.012499999999999956,6031.806747436523,4302,2035,2250,2035,3077,2544,400,3874,2036,400,2215,3390,2141,2793,4683,2061,0,0,3.4482758045196533,3.4482758045196533,3.4482758045196533,0,3.4482758045196533,3.4482758045196533,0,0,0,0,3.4482758045196533,3.4482758045196533,0,3.4482758045196533,15930789888,0,4163850240,0
200,1707917275222,630.1992950439453,2050,2,0.9625,578.3302764892578,2050,2,0.825,526.123779296875,2050,2,0.825,640.6326599121094,2050,2,0.825,618.1171875,2050,2,0.825,820.4413299560547,2050,2,0.825,537.6294250488281,5125,0,0.825,540.7743377685547,2050,2,0.825,6032.129318237305,4302,2035,2250,2035,3077,2544,400,3874,2036,400,2215,3390,2141,2793,4683,2061,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,15930789888,0,4163850240,0
> ... (some left out lines) ...
> 200,1707917279836,630.3352203369141,2050,2,0.9625,578.5105285644531,2050,2,0.68125,526.2675476074219,2050,2,0.68125,640.8289337158203,2050,2,0.68125,618.3496704101563,2050,2,0.68125,821.4627685546875,2050,2,0.68125,538.1986999511719,5125,0,0.68125,541.3470306396484,5125,0,0.68125,6037.511184692383,4302,2035,2250,2035,3077,2544,400,3874,2036,400,2215,3390,2141,2793,4683,2061,0,0,0,0,0,0,4.761904716491699,0,0,0,0,5,4.761904716491699,0,0,0,15930789888,0,4155834368,0

There was supposed to be a summary at the end of the output. However, there is none shown.

**Comment by tdurieux** [comment]
It is indeed not supported for your system. We need to extend the support here: https://github.com/tdurieux/EnergiBridge/blob/main/src/main.rs#L116
